name: Deploy Lost Tails
on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint-and-build:
    environment:
      name: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat > .env << EOF
          VITE_API_KEY=${{ secrets.VITE_API_KEY }}
          VITE_AUTH_DOMAIN=${{ secrets.VITE_AUTH_DOMAIN }}
          VITE_PROJECT_ID=${{ secrets.VITE_PROJECT_ID }}
          VITE_STORAGE_BUCKET=${{ secrets.VITE_STORAGE_BUCKET }}
          VITE_MESSAGING_SENDER_ID=${{ secrets.VITE_MESSAGING_SENDER_ID }}
          VITE_APP_ID=${{ secrets.VITE_APP_ID }}
          VITE_PET_FINDER_API_KEY=${{ secrets.VITE_PET_FINDER_API_KEY }}
          VITE_PET_FINDER_SECRET=${{ secrets.VITE_PET_FINDER_SECRET }}
        shell: bash

      - name: Install Dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi
      
      - name: Lint Project
        run: |
          if [ -f package.json ]; then
            npm run lint
          fi

      - name: Build Project
        run: |
          if [ -f package.json ]; then
            npm run build
          fi


  build-and-deploy:
    needs: lint-and-build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat > .env << EOF
          VITE_API_KEY=${{ secrets.VITE_API_KEY }}
          VITE_AUTH_DOMAIN=${{ secrets.VITE_AUTH_DOMAIN }}
          VITE_PROJECT_ID=${{ secrets.VITE_PROJECT_ID }}
          VITE_STORAGE_BUCKET=${{ secrets.VITE_STORAGE_BUCKET }}
          VITE_MESSAGING_SENDER_ID=${{ secrets.VITE_MESSAGING_SENDER_ID }}
          VITE_APP_ID=${{ secrets.VITE_APP_ID }}
          VITE_PET_FINDER_API_KEY=${{ secrets.VITE_PET_FINDER_API_KEY }}
          VITE_PET_FINDER_SECRET=${{ secrets.VITE_PET_FINDER_SECRET }}
        shell: bash

      - name: Install Dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Build Project
        run: |
          if [ -f package.json ]; then
            npm run build
          fi

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
